{ pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    vim
    wget
    ffmpeg
    grimblast
    wl-clipboard
    atuin
    prismlauncher
    jetbrains.idea-community-bin
    exodus
    vscodium
    direnv
    spicetify-cli
    discord
    ghostty
    kitty
    alacritty
    zed-editor
    btop
    fastfetch
    # neovim removed - now managed in home.nix
    xfce.thunar
    git
    rofi-wayland
    waybar
    gsettings-desktop-schemas
    glib
    dconf-editor
    gnome-themes-extra
    libsForQt5.qt5ct
    qt6ct
    libsForQt5.qtstyleplugin-kvantum
    qt6Packages.qtstyleplugin-kvantum
    adwaita-qt
    adwaita-qt6
    pkgs.os-prober
    inputs.zen-browser.packages.${pkgs.system}.default
    inputs.swww.packages.${pkgs.system}.swww
  ];
}
