{ ... }:
let
  vars = import ./../../../_config.nix;
in
{
  hjem.users.${vars.username}.files = {
    ".config-hyprland/noctalia/templates/zed-theme.json".text = ''
      {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": "Noctalia",
        "author": "noctalia",
        "themes": [
          {
            "name": "Noctalia Dark",
            "appearance": "dark",
            "style": {
              "background": "{{colors.surface.default.hex}}",
              "background.appearance": "opaque",

              "border": "{{colors.outline_variant.default.hex}}",
              "border.variant": "{{colors.outline_variant.default.hex}}",
              "border.focused": "{{colors.primary.default.hex}}",
              "border.selected": "{{colors.primary.default.hex}}",
              "border.transparent": "{{colors.surface.default.hex}}00",
              "border.disabled": "{{colors.outline_variant.default.hex}}50",

              "elevated_surface.background": "{{colors.surface_container_high.default.hex}}",
              "surface.background": "{{colors.surface_variant.default.hex}}",
              "panel.background": "{{colors.surface.default.hex}}",
              "panel.focused_border": "{{colors.primary.default.hex}}",
              "panel.indent_guide": "{{colors.outline_variant.default.hex}}40",
              "panel.indent_guide_active": "{{colors.outline.default.hex}}",
              "panel.indent_guide_hover": "{{colors.outline_variant.default.hex}}80",

              "pane.focused_border": "{{colors.primary.default.hex}}",
              "pane_group.border": "{{colors.outline_variant.default.hex}}",

              "tab_bar.background": "{{colors.surface.default.hex}}",
              "tab.active_background": "{{colors.surface_variant.default.hex}}",
              "tab.inactive_background": "{{colors.surface.default.hex}}",
              "toolbar.background": "{{colors.surface.default.hex}}",
              "title_bar.background": "{{colors.surface.default.hex}}",
              "title_bar.inactive_background": "{{colors.surface_variant.default.hex}}",
              "status_bar.background": "{{colors.surface.default.hex}}",

              "text": "{{colors.on_surface.default.hex}}",
              "text.muted": "{{colors.on_surface_variant.default.hex}}",
              "text.placeholder": "{{colors.on_surface_variant.default.hex}}80",
              "text.disabled": "{{colors.on_surface_variant.default.hex}}50",
              "text.accent": "{{colors.primary.default.hex}}",

              "icon": "{{colors.on_surface_variant.default.hex}}",
              "icon.muted": "{{colors.on_surface_variant.default.hex}}80",
              "icon.disabled": "{{colors.on_surface_variant.default.hex}}50",
              "icon.placeholder": "{{colors.on_surface_variant.default.hex}}60",
              "icon.accent": "{{colors.primary.default.hex}}",

              "element.background": "{{colors.surface_variant.default.hex}}",
              "element.hover": "{{colors.surface_variant.default.hex}}80",
              "element.active": "{{colors.primary.default.hex}}50",
              "element.selected": "{{colors.primary.default.hex}}30",
              "element.disabled": "{{colors.surface_variant.default.hex}}40",

              "ghost_element.background": "{{colors.surface.default.hex}}00",
              "ghost_element.hover": "{{colors.surface_variant.default.hex}}80",
              "ghost_element.active": "{{colors.primary.default.hex}}50",
              "ghost_element.selected": "{{colors.primary.default.hex}}30",
              "ghost_element.disabled": "{{colors.surface_variant.default.hex}}40",

              "drop_target.background": "{{colors.primary.default.hex}}20",

              "editor.background": "{{colors.surface.default.hex}}",
              "editor.foreground": "{{colors.on_surface.default.hex}}",
              "editor.gutter.background": "{{colors.surface.default.hex}}",
              "editor.subheader.background": "{{colors.surface_variant.default.hex}}",
              "editor.active_line.background": "{{colors.surface_variant.default.hex}}40",
              "editor.highlighted_line.background": "{{colors.primary.default.hex}}15",
              "editor.line_number": "{{colors.on_surface_variant.default.hex}}",
              "editor.active_line_number": "{{colors.on_surface.default.hex}}",
              "editor.hover_line_number": "{{colors.on_surface.default.hex}}80",
              "editor.invisible": "{{colors.on_surface_variant.default.hex}}40",
              "editor.wrap_guide": "{{colors.outline_variant.default.hex}}40",
              "editor.active_wrap_guide": "{{colors.outline_variant.default.hex}}80",
              "editor.indent_guide": "{{colors.outline_variant.default.hex}}40",
              "editor.indent_guide_active": "{{colors.outline.default.hex}}",
              "editor.document_highlight.read_background": "{{colors.primary.default.hex}}20",
              "editor.document_highlight.write_background": "{{colors.secondary.default.hex}}20",
              "editor.document_highlight.bracket_background": "{{colors.tertiary.default.hex}}20",

              "terminal.background": "{{colors.surface.default.hex}}",
              "terminal.foreground": "{{colors.on_surface.default.hex}}",
              "terminal.bright_foreground": "{{colors.on_surface.default.hex}}",
              "terminal.dim_foreground": "{{colors.on_surface_variant.default.hex}}",
              "terminal.ansi.background": "{{colors.surface.default.hex}}",
              "terminal.ansi.black": "{{colors.surface_variant.default.hex}}",
              "terminal.ansi.bright_black": "{{colors.on_surface_variant.default.hex}}",
              "terminal.ansi.dim_black": "{{colors.surface_variant.default.hex}}80",
              "terminal.ansi.red": "{{colors.error.default.hex}}",
              "terminal.ansi.bright_red": "{{colors.error.default.hex}}",
              "terminal.ansi.dim_red": "{{colors.error.default.hex}}80",
              "terminal.ansi.green": "{{colors.secondary.default.hex}}",
              "terminal.ansi.bright_green": "{{colors.secondary.default.hex}}",
              "terminal.ansi.dim_green": "{{colors.secondary.default.hex}}80",
              "terminal.ansi.yellow": "{{colors.tertiary.default.hex}}",
              "terminal.ansi.bright_yellow": "{{colors.tertiary.default.hex}}",
              "terminal.ansi.dim_yellow": "{{colors.tertiary.default.hex}}80",
              "terminal.ansi.blue": "{{colors.primary.default.hex}}",
              "terminal.ansi.bright_blue": "{{colors.primary.default.hex}}",
              "terminal.ansi.dim_blue": "{{colors.primary.default.hex}}80",
              "terminal.ansi.magenta": "{{colors.primary_container.default.hex}}",
              "terminal.ansi.bright_magenta": "{{colors.primary_container.default.hex}}",
              "terminal.ansi.dim_magenta": "{{colors.primary_container.default.hex}}80",
              "terminal.ansi.cyan": "{{colors.secondary_container.default.hex}}",
              "terminal.ansi.bright_cyan": "{{colors.secondary_container.default.hex}}",
              "terminal.ansi.dim_cyan": "{{colors.secondary_container.default.hex}}80",
              "terminal.ansi.white": "{{colors.on_surface.default.hex}}",
              "terminal.ansi.bright_white": "{{colors.on_surface.default.hex}}",
              "terminal.ansi.dim_white": "{{colors.on_surface.default.hex}}80",

              "scrollbar.thumb.background": "{{colors.outline_variant.default.hex}}",
              "scrollbar.thumb.hover_background": "{{colors.outline.default.hex}}",
              "scrollbar.thumb.active_background": "{{colors.primary.default.hex}}",
              "scrollbar.thumb.border": "{{colors.surface.default.hex}}00",
              "scrollbar.track.background": "{{colors.surface.default.hex}}00",
              "scrollbar.track.border": "{{colors.outline_variant.default.hex}}20",

              "search.match_background": "{{colors.primary.default.hex}}30",
              "search.active_match_background": "{{colors.primary.default.hex}}60",
              "link_text.hover": "{{colors.primary.default.hex}}",

              "version_control.added": "{{colors.secondary.default.hex}}",
              "version_control.modified": "{{colors.primary.default.hex}}",
              "version_control.deleted": "{{colors.error.default.hex}}",

              "conflict": "{{colors.tertiary.default.hex}}",
              "conflict.background": "{{colors.tertiary.default.hex}}15",
              "conflict.border": "{{colors.tertiary.default.hex}}50",
              "created": "{{colors.secondary.default.hex}}",
              "created.background": "{{colors.secondary.default.hex}}15",
              "created.border": "{{colors.secondary.default.hex}}50",
              "deleted": "{{colors.error.default.hex}}",
              "deleted.background": "{{colors.error.default.hex}}15",
              "deleted.border": "{{colors.error.default.hex}}50",
              "modified": "{{colors.primary.default.hex}}",
              "modified.background": "{{colors.primary.default.hex}}15",
              "modified.border": "{{colors.primary.default.hex}}50",
              "renamed": "{{colors.secondary.default.hex}}",
              "renamed.background": "{{colors.secondary.default.hex}}15",
              "renamed.border": "{{colors.secondary.default.hex}}50",
              "hidden": "{{colors.on_surface_variant.default.hex}}80",
              "hidden.background": "{{colors.surface.default.hex}}",
              "hidden.border": "{{colors.outline_variant.default.hex}}",
              "ignored": "{{colors.on_surface_variant.default.hex}}60",
              "ignored.background": "{{colors.surface.default.hex}}",
              "ignored.border": "{{colors.outline_variant.default.hex}}",

              "error": "{{colors.error.default.hex}}",
              "error.background": "{{colors.error.default.hex}}15",
              "error.border": "{{colors.error.default.hex}}50",
              "warning": "{{colors.tertiary.default.hex}}",
              "warning.background": "{{colors.tertiary.default.hex}}15",
              "warning.border": "{{colors.tertiary.default.hex}}50",
              "success": "{{colors.secondary.default.hex}}",
              "success.background": "{{colors.secondary.default.hex}}15",
              "success.border": "{{colors.secondary.default.hex}}50",
              "info": "{{colors.primary.default.hex}}",
              "info.background": "{{colors.primary.default.hex}}15",
              "info.border": "{{colors.primary.default.hex}}50",
              "hint": "{{colors.on_surface_variant.default.hex}}",
              "hint.background": "{{colors.surface_variant.default.hex}}",
              "hint.border": "{{colors.outline_variant.default.hex}}",
              "predictive": "{{colors.on_surface_variant.default.hex}}80",
              "predictive.background": "{{colors.surface.default.hex}}00",
              "predictive.border": "{{colors.surface.default.hex}}00",
              "unreachable": "{{colors.on_surface_variant.default.hex}}50",
              "unreachable.background": "{{colors.surface.default.hex}}",
              "unreachable.border": "{{colors.outline_variant.default.hex}}",

              "players": [
                { "cursor": "{{colors.primary.default.hex}}", "background": "{{colors.primary.default.hex}}", "selection": "{{colors.primary.default.hex}}3d" },
                { "cursor": "{{colors.secondary.default.hex}}", "background": "{{colors.secondary.default.hex}}", "selection": "{{colors.secondary.default.hex}}3d" },
                { "cursor": "{{colors.tertiary.default.hex}}", "background": "{{colors.tertiary.default.hex}}", "selection": "{{colors.tertiary.default.hex}}3d" },
                { "cursor": "{{colors.error.default.hex}}", "background": "{{colors.error.default.hex}}", "selection": "{{colors.error.default.hex}}3d" },
                { "cursor": "{{colors.on_surface.default.hex}}", "background": "{{colors.on_surface.default.hex}}", "selection": "{{colors.on_surface.default.hex}}3d" },
                { "cursor": "{{colors.primary_container.default.hex}}", "background": "{{colors.primary_container.default.hex}}", "selection": "{{colors.primary_container.default.hex}}3d" },
                { "cursor": "{{colors.secondary_container.default.hex}}", "background": "{{colors.secondary_container.default.hex}}", "selection": "{{colors.secondary_container.default.hex}}3d" },
                { "cursor": "{{colors.outline.default.hex}}", "background": "{{colors.outline.default.hex}}", "selection": "{{colors.outline.default.hex}}3d" }
              ],

              "syntax": {
                "attribute": { "color": "{{colors.secondary.default.hex}}" },
                "boolean": { "color": "{{colors.primary.default.hex}}" },
                "comment": { "color": "{{colors.on_surface_variant.default.hex}}", "font_style": "italic" },
                "comment.doc": { "color": "{{colors.on_surface_variant.default.hex}}", "font_style": "italic" },
                "constant": { "color": "{{colors.tertiary.default.hex}}" },
                "constructor": { "color": "{{colors.tertiary.default.hex}}" },
                "diff.plus": { "color": "{{colors.secondary.default.hex}}" },
                "diff.minus": { "color": "{{colors.error.default.hex}}" },
                "embedded": { "color": "{{colors.secondary_container.default.hex}}" },
                "emphasis": { "color": "{{colors.primary.default.hex}}", "font_style": "italic" },
                "emphasis.strong": { "color": "{{colors.primary.default.hex}}", "font_weight": 700 },
                "enum": { "color": "{{colors.tertiary.default.hex}}" },
                "function": { "color": "{{colors.tertiary.default.hex}}" },
                "function.builtin": { "color": "{{colors.error.default.hex}}" },
                "function.method": { "color": "{{colors.tertiary.default.hex}}" },
                "hint": { "color": "{{colors.on_surface_variant.default.hex}}" },
                "keyword": { "color": "{{colors.primary.default.hex}}", "font_weight": 700 },
                "label": { "color": "{{colors.secondary.default.hex}}" },
                "link_text": { "color": "{{colors.secondary_container.default.hex}}", "font_style": "italic" },
                "link_uri": { "color": "{{colors.primary_container.default.hex}}" },
                "namespace": { "color": "{{colors.secondary.default.hex}}" },
                "number": { "color": "{{colors.tertiary.default.hex}}" },
                "operator": { "color": "{{colors.primary.default.hex}}" },
                "predictive": { "color": "{{colors.on_surface_variant.default.hex}}80", "font_style": "italic" },
                "preproc": { "color": "{{colors.error.default.hex}}" },
                "primary": { "color": "{{colors.on_surface.default.hex}}" },
                "property": { "color": "{{colors.on_surface.default.hex}}" },
                "punctuation": { "color": "{{colors.on_surface_variant.default.hex}}" },
                "punctuation.bracket": { "color": "{{colors.on_surface_variant.default.hex}}" },
                "punctuation.delimiter": { "color": "{{colors.on_surface_variant.default.hex}}" },
                "punctuation.list_marker": { "color": "{{colors.on_surface.default.hex}}" },
                "punctuation.markup": { "color": "{{colors.secondary.default.hex}}" },
                "punctuation.special": { "color": "{{colors.on_surface_variant.default.hex}}" },
                "selector": { "color": "{{colors.tertiary.default.hex}}" },
                "selector.pseudo": { "color": "{{colors.secondary.default.hex}}" },
                "string": { "color": "{{colors.secondary.default.hex}}" },
                "string.escape": { "color": "{{colors.tertiary.default.hex}}" },
                "string.regex": { "color": "{{colors.tertiary.default.hex}}" },
                "string.special": { "color": "{{colors.primary_container.default.hex}}" },
                "string.special.symbol": { "color": "{{colors.secondary_container.default.hex}}" },
                "tag": { "color": "{{colors.primary.default.hex}}" },
                "text.literal": { "color": "{{colors.secondary.default.hex}}" },
                "title": { "color": "{{colors.tertiary.default.hex}}", "font_weight": 700 },
                "type": { "color": "{{colors.secondary.default.hex}}" },
                "type.builtin": { "color": "{{colors.secondary.default.hex}}", "font_weight": 700 },
                "variable": { "color": "{{colors.on_surface.default.hex}}" },
                "variable.special": { "color": "{{colors.primary.default.hex}}" },
                "variant": { "color": "{{colors.secondary.default.hex}}" }
              }
            }
          }
        ]
      }
    '';
  };
}
