{ ... }:
let
  vars = import ./../../../_config.nix;
in
{
  hjem.users.${vars.username}.files = {
    ".config/matugen/templates/nvim-dms-colors.lua".text = ''
      -- generated by dms matugen — do not edit manually
      vim.cmd("highlight clear")
      vim.opt.background = "dark"

      local function darken(hex, amount)
        local r = tonumber(hex:sub(2,3), 16)
        local g = tonumber(hex:sub(4,5), 16)
        local b = tonumber(hex:sub(6,7), 16)
        r = math.max(0, math.floor(r * amount))
        g = math.max(0, math.floor(g * amount))
        b = math.max(0, math.floor(b * amount))
        return string.format("#%02x%02x%02x", r, g, b)
      end

      local primary     = "{{colors.primary.default.hex}}"
      local sec_cont    = "{{colors.secondary_container.default.hex}}"

      local c = {
        bg          = darken(primary, 0.15),
        bg_dark     = darken(primary, 0.15),
        bg_highlight= "{{colors.secondary_container.default.hex}}",
        fg          = "{{colors.on_surface.default.hex}}",
        fg_muted    = "{{colors.on_surface_variant.default.hex}}",
        primary     = "{{colors.primary.default.hex}}",
        secondary   = "{{colors.secondary.default.hex}}",
        tertiary    = "{{colors.tertiary.default.hex}}",
        error       = "{{colors.error.default.hex}}",
        outline     = "{{colors.outline.default.hex}}",
        outline_var = "{{colors.outline_variant.default.hex}}",
        p_container = "{{colors.primary_container.default.hex}}",
        s_container = "{{colors.secondary_container.default.hex}}",
      }

      local hi = function(group, opts)
        vim.api.nvim_set_hl(0, group, opts)
      end

      -- editor chrome
      hi("Normal",        { fg = c.fg,       bg = c.bg })
      hi("NormalFloat",   { fg = c.fg,       bg = c.bg_dark })
      hi("FloatBorder",   { fg = c.outline,  bg = c.bg_dark })
      hi("CursorLine",    { bg = c.bg_highlight })
      hi("CursorLineNr",  { fg = c.primary,  bold = true })
      hi("LineNr",        { fg = c.fg_muted })
      hi("SignColumn",    { bg = c.bg })
      hi("StatusLine",    { fg = c.fg,       bg = c.bg_dark })
      hi("StatusLineNC",  { fg = c.fg_muted, bg = c.bg_dark })
      hi("TabLine",       { fg = c.fg_muted, bg = c.bg_dark })
      hi("TabLineSel",    { fg = c.fg,       bg = c.bg_highlight })
      hi("TabLineFill",   { bg = c.bg_dark })
      hi("WinSeparator",  { fg = c.outline_var })
      hi("Pmenu",         { fg = c.fg,       bg = c.bg_dark })
      hi("PmenuSel",      { fg = c.fg,       bg = c.bg_highlight, bold = true })
      hi("PmenuSbar",     { bg = c.bg_dark })
      hi("PmenuThumb",    { bg = c.outline_var })
      hi("Visual",        { bg = c.bg_highlight })
      hi("Search",        { fg = c.bg,       bg = c.primary })
      hi("IncSearch",     { fg = c.bg,       bg = c.tertiary })
      hi("MatchParen",    { fg = c.tertiary, bold = true })

      -- syntax
      hi("Comment",       { fg = c.fg_muted, italic = true })
      hi("Constant",      { fg = c.tertiary })
      hi("String",        { fg = c.secondary })
      hi("Character",     { fg = c.secondary })
      hi("Number",        { fg = c.tertiary })
      hi("Boolean",       { fg = c.primary })
      hi("Float",         { fg = c.tertiary })
      hi("Identifier",    { fg = c.fg })
      hi("Function",      { fg = c.tertiary })
      hi("Statement",     { fg = c.primary,  bold = true })
      hi("Keyword",       { fg = c.primary,  bold = true })
      hi("Conditional",   { fg = c.primary,  bold = true })
      hi("Repeat",        { fg = c.primary,  bold = true })
      hi("Operator",      { fg = c.primary })
      hi("PreProc",       { fg = c.error })
      hi("Include",       { fg = c.primary })
      hi("Define",        { fg = c.primary })
      hi("Type",          { fg = c.secondary })
      hi("StorageClass",  { fg = c.secondary })
      hi("Structure",     { fg = c.secondary })
      hi("Special",       { fg = c.p_container })
      hi("Delimiter",     { fg = c.fg_muted })
      hi("Underlined",    { underline = true })
      hi("Error",         { fg = c.error })
      hi("Todo",          { fg = c.tertiary, bold = true })

      -- treesitter
      hi("@variable",             { fg = c.fg })
      hi("@variable.builtin",     { fg = c.primary })
      hi("@variable.parameter",   { fg = c.fg })
      hi("@variable.member",      { fg = c.fg })
      hi("@constant",             { fg = c.tertiary })
      hi("@constant.builtin",     { fg = c.tertiary })
      hi("@string",               { fg = c.secondary })
      hi("@string.escape",        { fg = c.tertiary })
      hi("@string.special",       { fg = c.p_container })
      hi("@number",               { fg = c.tertiary })
      hi("@boolean",              { fg = c.primary })
      hi("@function",             { fg = c.tertiary })
      hi("@function.builtin",     { fg = c.error })
      hi("@function.method",      { fg = c.tertiary })
      hi("@function.call",        { fg = c.tertiary })
      hi("@keyword",              { fg = c.primary, bold = true })
      hi("@keyword.import",       { fg = c.primary })
      hi("@keyword.return",       { fg = c.primary, bold = true })
      hi("@operator",             { fg = c.primary })
      hi("@punctuation",          { fg = c.fg_muted })
      hi("@punctuation.bracket",  { fg = c.fg_muted })
      hi("@punctuation.delimiter",{ fg = c.fg_muted })
      hi("@type",                 { fg = c.secondary })
      hi("@type.builtin",         { fg = c.secondary, bold = true })
      hi("@namespace",            { fg = c.secondary })
      hi("@attribute",            { fg = c.secondary })
      hi("@constructor",          { fg = c.tertiary })
      hi("@tag",                  { fg = c.primary })
      hi("@tag.attribute",        { fg = c.secondary })
      hi("@tag.delimiter",        { fg = c.fg_muted })
      hi("@comment",              { fg = c.fg_muted, italic = true })
      hi("@markup.heading",       { fg = c.tertiary, bold = true })
      hi("@markup.link",          { fg = c.secondary, italic = true })
      hi("@markup.raw",           { fg = c.s_container })

      -- diagnostics
      hi("DiagnosticError",          { fg = c.error })
      hi("DiagnosticWarn",           { fg = c.tertiary })
      hi("DiagnosticInfo",           { fg = c.primary })
      hi("DiagnosticHint",           { fg = c.fg_muted })
      hi("DiagnosticUnderlineError", { sp = c.error,    underline = true })
      hi("DiagnosticUnderlineWarn",  { sp = c.tertiary, underline = true })
      hi("DiagnosticUnderlineInfo",  { sp = c.primary,  underline = true })
      hi("DiagnosticUnderlineHint",  { sp = c.fg_muted, underline = true })

      -- which-key
      hi("WhichKey",          { fg = c.primary })
      hi("WhichKeyDesc",      { fg = c.fg })
      hi("WhichKeyGroup",     { fg = c.secondary, bold = true })
      hi("WhichKeySeparator", { fg = c.fg_muted })
      hi("WhichKeyNormal",    { fg = c.fg,       bg = c.bg_dark })
      hi("WhichKeyBorder",    { fg = c.outline,  bg = c.bg_dark })
      hi("WhichKeyTitle",     { fg = c.tertiary, bold = true })
      hi("WhichKeyIcon",      { fg = c.primary })
    '';
  };
}
